# Instruction

---
###To use this app, you need to use the left side controls to enter your personal data, in order to manipulate the input variables.

###In the right part, you will see your entered personal information, and and the predicted value. 

###This predicted value will be displayed as numeric information, and as a graph for a better understanding of the results.

###The results are reactive, and the predicted value and the graph will change in the moment that you start introducing the data.


####Note:

####The prediction algorithm uses information from the Framingham Heart Study to predict a person's chance of developing cardiovascular disease in the next 10 years.
####More data about the Framingham Heart Study is available  here - https://en.wikipedia.org/wiki/Framingham_Risk_Score

####For this app prediction we will use just a subset from the Framingham database, using just the most important columns that can influence the prediction results.

####The substructure of the modified database used in this application is available in the Prediction Database Structure tab, and some sample values are available in the Prediction Database Head tab.
